### PR TITLE
Content Length and incorrect Content-Type fixes

### LINKED ISSUE #17: Inbound: gracefully handle incorrect Content-Type header
https://app.honeybadger.io/projects/2160/faults/15872532#notice-trace

If a caller provides the wrong Content-Type header, then the inbound integration throws an error. It would be better to respond to the caller with "The request header indicates that the body contains XML. But it does not." Or something.

### PR DESCRIPTION
**Pull request by zalary**
resolves #17 and #18

### CODE REVIEW

File: src/inbound.coffee [hunk 1]
```diff
@@ -70,6 +70,10 @@ request = (req) ->
       unless supportedMimeTypeLookup[mimeType]?
         throw new HttpError(406, {'Content-Type': 'text/plain'}, "MIME type in Content-Type header is not supported. Use only #{supportedMimeTypes.join(', ')}.")
 
+      # ensure content length matches body length
+      if req.headers['Content-Length'] != req.body.length
+        throw new HttpError(400, {'Content-Type': 'text/plain'}, 'Declared Content-Length header does not match actual body length.')
```
Comment (alexkwolfe) [inline src/inbound.coffee]: This strict test makes me nervous. The situation that I was talking about in issue #18, is that when the Content-Length header is 0, then don't try to parse the body.

**Comment by cgrayson** [comment]
Aside from `Content-Length` discussion, LGTM

File: src/inbound.coffee (hunk 1 above)
Comment (zalary) [inline src/inbound.coffee]: I can adjust it so that we only don't parse if the Content-Length is 0, but I guess I don't understand allowing an invalid request in some cases.

Comment (alexkwolfe) [inline src/inbound.coffee]: Handling incorrect Content-Length is something the framework should be doing. Maybe another way to put this is: if someone posts a lead and there is a Content-Type header but no request body, then don't try to parse the body. What's happening is that someone includes a Content-Type header, and the integration assumes that there is content. Then it shits the bed trying to parse an empty string to XML.

Comment (alexkwolfe) [inline src/inbound.coffee]: Or better yet: don't try to parse an empty body.

File: src/inbound.coffee [hunk 2]
```diff
@@ -79,7 +80,12 @@ request = (req) ->
 
       # if XML, turn doc into an object
       if mimeType == 'application/xml' or mimeType == 'text/xml'
-        parsed = parsed.toObject(explicitArray: false, explicitRoot: false, mergeAttrs: true)
+        try
+          parsed = parsed.toObject(explicitArray: false, explicitRoot: false, mergeAttrs: true)
+        catch e
+          xmlError = e.toString().split('.')
```
Comment (alexkwolfe) [inline src/inbound.coffee]: Curious why you'e doing the toString() and split here.

Comment (zalary) [inline src/inbound.coffee]: Because it returns an ugly error with linebreaks in an array 

[Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: x]

which granted may be useful in some other cases, though it's not in this case.  I could just strip the line breaks and return the whole thing

Comment (alexkwolfe) [inline src/inbound.coffee]: What does e.message resolve to?

Comment (zalary) [inline src/inbound.coffee]: it resolves to the same thing, but as a typeof string instead of a typeof object

[Error: Non-whitespace before first tag.
Line: 0
Column: 1
Char: x]

vs 

Non-whitespace before first tag.
Line: 0
Column: 1
Char: x

Comment (alexkwolfe) [inline src/inbound.coffee]: Got it.

**Comment by alexkwolfe** [comment]
LGTM
